/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './app/**/*.{js,ts,jsx,tsx,mdx}',
        './components/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'on-surface-variant': '#404946',
                'surface-bright': '#fcf9f8',
                'on-primary-container': '#75a799',
                'on-tertiary': '#ffffff',
                'surface-container': '#f0eded',
                'surface-tint': '#36675b',
                'tertiary-fixed': '#e4e2de',
                'inverse-primary': '#9ed1c3',
                'surface-container-highest': '#e5e2e1',
                'on-secondary-fixed-variant': '#5d4201',
                'secondary-fixed-dim': '#e9c176',
                background: '#fcf9f8',
                tertiary: '#1f201e',
                'on-surface': '#1c1b1b',
                'on-primary': '#ffffff',
                outline: '#707976',
                'on-background': '#1c1b1b',
                'error-container': '#ffdad6',
                'on-error-container': '#93000a',
                'outline-variant': '#c0c8c4',
                'surface-variant': '#e5e2e1',
                'on-tertiary-container': '#9e9d9a',
                'surface-container-lowest': '#ffffff',
                secondary: '#775a19',
                'surface-container-low': '#f6f3f2',
                'tertiary-fixed-dim': '#c8c6c3',
                'surface-dim': '#dcd9d9',
                'secondary-container': '#fed488',
                'on-secondary-fixed': '#261900',
                surface: '#fcf9f8',
                'primary-container': '#023c32',
                'tertiary-container': '#343532',
                error: '#ba1a1a',
                'secondary-fixed': '#ffdea5',
                'on-secondary-container': '#785a1a',
                'on-secondary': '#ffffff',
                'inverse-surface': '#313030',
                'surface-container-high': '#eae7e7',
                primary: '#00251e',
                'on-primary-fixed': '#00201a',
                'on-primary-fixed-variant': '#1c4f44',
                'on-tertiary-fixed': '#1b1c1a',
                'on-error': '#ffffff',
                'inverse-on-surface': '#f3f0ef',
                'primary-fixed': '#b9edde',
                'primary-fixed-dim': '#9ed1c3',
                'on-tertiary-fixed-variant': '#474744',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
            spacing: {
                'margin-mobile': '20px',
                unit: '8px',
                'container-max': '1280px',
                'stack-sm': '12px',
                'margin-desktop': '64px',
                'stack-lg': '40px',
                gutter: '24px',
                'stack-md': '24px',
            },
            fontFamily: {
                'display-lg-mobile': ['var(--font-eb-garamond)'],
                'body-lg': ['var(--font-manrope)'],
                'headline-sm': ['var(--font-eb-garamond)'],
                'label-sm': ['var(--font-manrope)'],
                'label-md': ['var(--font-manrope)'],
                'headline-md': ['var(--font-eb-garamond)'],
                'display-lg': ['var(--font-eb-garamond)'],
                'body-md': ['var(--font-manrope)'],
            },
            fontSize: {
                'display-lg-mobile': [
                    '40px',
                    { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '500' },
                ],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '500' }],
                'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
                'label-md': [
                    '14px',
                    { lineHeight: '20px', letterSpacing: '0.1em', fontWeight: '600' },
                ],
                'headline-md': ['32px', { lineHeight: '40px', fontWeight: '500' }],
                'display-lg': [
                    '64px',
                    { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '500' },
                ],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
            },
        },
    },
    plugins: [],
};