// Searchable country list used by the checkout country dropdown and the phone
// number country-code picker. Each entry carries the ISO 3166-1 alpha-2 code
// (for the flag), the display name, and the international dial code.
export const COUNTRIES = [
    { code: 'PK', name: 'Pakistan', dialCode: '+92' },
    { code: 'US', name: 'United States', dialCode: '+1' },
    { code: 'GB', name: 'United Kingdom', dialCode: '+44' },
    { code: 'AE', name: 'United Arab Emirates', dialCode: '+971' },
    { code: 'SA', name: 'Saudi Arabia', dialCode: '+966' },
    { code: 'IN', name: 'India', dialCode: '+91' },
    { code: 'CN', name: 'China', dialCode: '+86' },
    { code: 'JP', name: 'Japan', dialCode: '+81' },
    { code: 'KR', name: 'South Korea', dialCode: '+82' },
    { code: 'DE', name: 'Germany', dialCode: '+49' },
    { code: 'FR', name: 'France', dialCode: '+33' },
    { code: 'IT', name: 'Italy', dialCode: '+39' },
    { code: 'ES', name: 'Spain', dialCode: '+34' },
    { code: 'PT', name: 'Portugal', dialCode: '+351' },
    { code: 'NL', name: 'Netherlands', dialCode: '+31' },
    { code: 'BE', name: 'Belgium', dialCode: '+32' },
    { code: 'CH', name: 'Switzerland', dialCode: '+41' },
    { code: 'AT', name: 'Austria', dialCode: '+43' },
    { code: 'IE', name: 'Ireland', dialCode: '+353' },
    { code: 'DK', name: 'Denmark', dialCode: '+45' },
    { code: 'SE', name: 'Sweden', dialCode: '+46' },
    { code: 'NO', name: 'Norway', dialCode: '+47' },
    { code: 'FI', name: 'Finland', dialCode: '+358' },
    { code: 'IS', name: 'Iceland', dialCode: '+354' },
    { code: 'PL', name: 'Poland', dialCode: '+48' },
    { code: 'CZ', name: 'Czech Republic', dialCode: '+420' },
    { code: 'SK', name: 'Slovakia', dialCode: '+421' },
    { code: 'HU', name: 'Hungary', dialCode: '+36' },
    { code: 'RO', name: 'Romania', dialCode: '+40' },
    { code: 'BG', name: 'Bulgaria', dialCode: '+359' },
    { code: 'GR', name: 'Greece', dialCode: '+30' },
    { code: 'RU', name: 'Russia', dialCode: '+7' },
    { code: 'TR', name: 'Turkey', dialCode: '+90' },
    { code: 'BY', name: 'Belarus', dialCode: '+375' },
    { code: 'BR', name: 'Brazil', dialCode: '+55' },
    { code: 'MX', name: 'Mexico', dialCode: '+52' },
    { code: 'CA', name: 'Canada', dialCode: '+1' },
    { code: 'AR', name: 'Argentina', dialCode: '+54' },
    { code: 'CL', name: 'Chile', dialCode: '+56' },
    { code: 'CO', name: 'Colombia', dialCode: '+57' },
    { code: 'PE', name: 'Peru', dialCode: '+51' },
    { code: 'VE', name: 'Venezuela', dialCode: '+58' },
    { code: 'AU', name: 'Australia', dialCode: '+61' },
    { code: 'NZ', name: 'New Zealand', dialCode: '+64' },
    { code: 'ZA', name: 'South Africa', dialCode: '+27' },
    { code: 'EG', name: 'Egypt', dialCode: '+20' },
    { code: 'MA', name: 'Morocco', dialCode: '+212' },
    { code: 'NG', name: 'Nigeria', dialCode: '+234' },
    { code: 'KE', name: 'Kenya', dialCode: '+254' },
    { code: 'GH', name: 'Ghana', dialCode: '+233' },
    { code: 'QA', name: 'Qatar', dialCode: '+974' },
    { code: 'KW', name: 'Kuwait', dialCode: '+965' },
    { code: 'BH', name: 'Bahrain', dialCode: '+973' },
    { code: 'OM', name: 'Oman', dialCode: '+968' },
    { code: 'LB', name: 'Lebanon', dialCode: '+961' },
    { code: 'JO', name: 'Jordan', dialCode: '+962' },
    { code: 'IQ', name: 'Iraq', dialCode: '+964' },
    { code: 'IR', name: 'Iran', dialCode: '+98' },
    { code: 'AF', name: 'Afghanistan', dialCode: '+93' },
    { code: 'BD', name: 'Bangladesh', dialCode: '+880' },
    { code: 'LK', name: 'Sri Lanka', dialCode: '+94' },
    { code: 'NP', name: 'Nepal', dialCode: '+977' },
    { code: 'MY', name: 'Malaysia', dialCode: '+60' },
    { code: 'SG', name: 'Singapore', dialCode: '+65' },
    { code: 'ID', name: 'Indonesia', dialCode: '+62' },
    { code: 'TH', name: 'Thailand', dialCode: '+66' },
    { code: 'VN', name: 'Vietnam', dialCode: '+84' },
    { code: 'PH', name: 'Philippines', dialCode: '+63' },
    { code: 'HK', name: 'Hong Kong', dialCode: '+852' },
    { code: 'TW', name: 'Taiwan', dialCode: '+886' },
    { code: 'KZ', name: 'Kazakhstan', dialCode: '+7' },
    { code: 'UZ', name: 'Uzbekistan', dialCode: '+998' },
    { code: 'IL', name: 'Israel', dialCode: '+972' },
    { code: 'CY', name: 'Cyprus', dialCode: '+357' },
    { code: 'MT', name: 'Malta', dialCode: '+356' },
    { code: 'LU', name: 'Luxembourg', dialCode: '+352' },
    { code: 'HR', name: 'Croatia', dialCode: '+385' },
    { code: 'RS', name: 'Serbia', dialCode: '+381' },
    { code: 'SI', name: 'Slovenia', dialCode: '+386' },
    { code: 'LT', name: 'Lithuania', dialCode: '+370' },
    { code: 'LV', name: 'Latvia', dialCode: '+371' },
    { code: 'EE', name: 'Estonia', dialCode: '+372' },
    { code: 'MD', name: 'Moldova', dialCode: '+373' },
    { code: 'GE', name: 'Georgia', dialCode: '+995' },
    { code: 'AM', name: 'Armenia', dialCode: '+374' },
    { code: 'AZ', name: 'Azerbaijan', dialCode: '+994' },
    { code: 'TJ', name: 'Tajikistan', dialCode: '+992' },
    { code: 'TM', name: 'Turkmenistan', dialCode: '+993' },
    { code: 'KG', name: 'Kyrgyzstan', dialCode: '+996' },
    { code: 'MN', name: 'Mongolia', dialCode: '+976' },
    { code: 'ET', name: 'Ethiopia', dialCode: '+251' },
    { code: 'TZ', name: 'Tanzania', dialCode: '+255' },
    { code: 'UG', name: 'Uganda', dialCode: '+256' },
    { code: 'ZW', name: 'Zimbabwe', dialCode: '+263' },
    { code: 'ZM', name: 'Zambia', dialCode: '+260' },
    { code: 'MW', name: 'Malawi', dialCode: '+265' },
    { code: 'MZ', name: 'Mozambique', dialCode: '+258' },
    { code: 'AO', name: 'Angola', dialCode: '+244' },
    { code: 'CD', name: 'DR Congo', dialCode: '+243' },
    { code: 'CM', name: 'Cameroon', dialCode: '+237' },
    { code: 'CI', name: "Côte d'Ivoire", dialCode: '+225' },
    { code: 'SN', name: 'Senegal', dialCode: '+221' },
    { code: 'ML', name: 'Mali', dialCode: '+223' },
    { code: 'BF', name: 'Burkina Faso', dialCode: '+226' },
    { code: 'TG', name: 'Togo', dialCode: '+228' },
    { code: 'BJ', name: 'Benin', dialCode: '+229' },
    { code: 'NE', name: 'Niger', dialCode: '+227' },
    { code: 'TD', name: 'Chad', dialCode: '+235' },
    { code: 'LY', name: 'Libya', dialCode: '+218' },
    { code: 'TN', name: 'Tunisia', dialCode: '+216' },
    { code: 'DZ', name: 'Algeria', dialCode: '+213' },
    { code: 'SD', name: 'Sudan', dialCode: '+249' },
    { code: 'SO', name: 'Somalia', dialCode: '+252' },
    { code: 'YE', name: 'Yemen', dialCode: '+967' },
    { code: 'SY', name: 'Syria', dialCode: '+963' },
    { code: 'PS', name: 'Palestine', dialCode: '+970' },
    { code: 'MV', name: 'Maldives', dialCode: '+960' },
    { code: 'BN', name: 'Brunei', dialCode: '+673' },
    { code: 'KH', name: 'Cambodia', dialCode: '+855' },
    { code: 'LA', name: 'Laos', dialCode: '+856' },
    { code: 'MM', name: 'Myanmar', dialCode: '+95' },
    { code: 'PG', name: 'Papua New Guinea', dialCode: '+675' },
    { code: 'FJ', name: 'Fiji', dialCode: '+679' },
    { code: 'BS', name: 'Bahamas', dialCode: '+1' },
    { code: 'JM', name: 'Jamaica', dialCode: '+1' },
    { code: 'TT', name: 'Trinidad and Tobago', dialCode: '+1' },
    { code: 'HT', name: 'Haiti', dialCode: '+509' },
    { code: 'DO', name: 'Dominican Republic', dialCode: '+1' },
    { code: 'CU', name: 'Cuba', dialCode: '+53' },
    { code: 'CR', name: 'Costa Rica', dialCode: '+506' },
    { code: 'PA', name: 'Panama', dialCode: '+507' },
    { code: 'UY', name: 'Uruguay', dialCode: '+598' },
    { code: 'PY', name: 'Paraguay', dialCode: '+595' },
    { code: 'BO', name: 'Bolivia', dialCode: '+591' },
    { code: 'EC', name: 'Ecuador', dialCode: '+593' },
    { code: 'GT', name: 'Guatemala', dialCode: '+502' },
    { code: 'SV', name: 'El Salvador', dialCode: '+503' },
    { code: 'HN', name: 'Honduras', dialCode: '+504' },
    { code: 'NI', name: 'Nicaragua', dialCode: '+505' },
];

// Default selections for the checkout form.
export const DEFAULT_COUNTRY = 'Pakistan';
export const DEFAULT_DIAL_CODE = '+92';

// Look up a country by its display name (used to keep saved-address values in sync).
export function findCountryByName(name) {
    if (!name) return null;
    return COUNTRIES.find(
        (c) => c.name.toLowerCase() === String(name).toLowerCase().trim()
    );
}
